### ISSUE TITLE
Exception handler middleware assumes stream immutability

### ISSUE THREAD

**Issue by AndrewCarterUK** [relayphp/Relay.Middleware#19]
[This class](https://github.com/relayphp/Relay.Middleware/blob/1.x/src/ExceptionHandler.php) should probably create a new response instance to avoid appending to anything written to the response before an exception was thrown.

**Comment by pmjones** [comment]
The ExceptionHandler receives a separate response object via constructor injection for that purpose. In the catch block, the handler returns the injected response. Does that cover your concern?

**Comment by AndrewCarterUK** [comment]
I didn't spot that (too quick on the skim), but I still think there is an issue there as the middleware isn't quite stateless.

There are a few scenarios where you may wish to execute a middleware multiple times (React PHP, Icicle, PHPFastCGI, etc...) and in this scenario there would be a problem.

That might not be a use case that you're concerned about, but I do think the middleware would be better stateless.

**Comment by pmjones** [comment]
> I do think the middleware would be better stateless.

Maybe, maybe not. I confess I am not thinking of async environments as a use case, mostly because I don't use them.

Regardless, I can't change the signature on this particular class, as the package is stable now. Two alternatives:
1. Start a 2.x branch, and pass a callable as factory to create an instance, instead of an already-created instance.
2. Create a new middleware in the 1.x branch that addresses your concerns.

PRs welcome for review in either case!

**Comment by AndrewCarterUK** [comment]
Another option would be to make zend-diactoros a concrete requirement (rather than a development requirement) and return a new response.

I'm happy to help with a PR for any of those options. I'm also happy to close the issue if you decide it's a use case that you don't want to support.

**Comment by pmjones** [comment]
Probably unwise to depend on Diactoros directly. A callable factory allows the user to create whatever kind of Response they like.

> I'm happy to help with a PR

Cool, I'll review it if/when you submit one.
